# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: API checker
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    name: API checker on OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
      fail-fast: false
      max-parallel: 64

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Cache local Maven repository
        uses: actions/cache@v6
        # https://github.com/actions/cache/blob/main/examples.md#java---maven
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # image(ubuntu-latest/ubuntu-24.04) included Java 8/11/17/21/25
      #   https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#java
      - name: Run API checker
        run: scripts/run_api_checker.sh
