# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: Strong CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    name: Strong CI on OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
      fail-fast: false
      max-parallel: 64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: brew install gnu-sed
        # https://docs.github.com/en/actions/learn-github-actions/variables#detecting-the-operating-system
        # https://docs.github.com/en/actions/learn-github-actions/expressions
        if: runner.os == 'macOS'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          # https://github.com/actions/setup-java?tab=readme-ov-file#install-multiple-jdks
          java-version: |
            8
            11
            17
            21
            23
          distribution: zulu
          cache: maven

      - name: Run integration test
        run: scripts/integration_test
      - name: Run integration of demos
        run: demos/scripts/integration_test

      - name: Remove self maven install files
        run: rm -rf $HOME/.m2/repository/io/foldright/cffu*

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Update TOC of markdown files contained TOC
        # https://github.com/thlorenz/doctoc
        run: |
          npm install -g doctoc
          npm list -g --depth=0
          scripts/update_md_toc.sh
      # https://remarkablemark.org/blog/2017/10/12/check-git-dirty/
      - name: Check git dirty
        run: |
          git status --short
          [ -z "$(git status --short)" ]
