# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: Strong CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    name: Strong CI on OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
      fail-fast: false
      max-parallel: 64

    steps:
      - run: sudo apt-get install ripgrep
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          # https://github.com/actions/setup-java?tab=readme-ov-file#install-multiple-jdks
          java-version: |
            8
            9
            10
            11
            17
            21
            24
          distribution: zulu
          cache: maven

      - name: Run integration test
        run: scripts/integration_test
      - name: Run integration of demos
        run: demos/scripts/integration_test

      - name: Remove self maven install files
        run: rm -rf $HOME/.m2/repository/io/foldright/cffu*
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5

      - name: Update TOC of markdown files contained TOC
        # https://github.com/thlorenz/doctoc
        run: |
          npm install -g doctoc
          npm list -g --depth=0
          scripts/update_md_toc.sh
      - name: Check API docs
        run: scripts/check_api_docs.sh
      - name: Check forbidden classes
        run: scripts/check_forbidden_classes.sh

      # https://remarkablemark.org/blog/2017/10/12/check-git-dirty/
      - name: Check git dirty
        run: |
          git status --short
          [ -z "$(git status --short)" ]
