# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: Fast CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    name: Fast CI on OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
      fail-fast: false
      max-parallel: 64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: microsoft
          cache: maven
      - name: Build and test with Java 21
        run: ./mvnw -V --no-transfer-progress clean install
